// Typed re-export of the bundled prompts.
//
// _prompts.json is generated by `npm run sync-prompts` from /prompts/*.md.
// Edit those .md files (not this one), then re-run the sync.

import promptData from "./_prompts.json" with { type: "json" };

export type Route = "code" | "writing" | "generic";

export const SYSTEM_PROMPTS: Record<Route, string> = {
  code:    promptData.code,
  writing: promptData.writing,
  generic: promptData.generic,
};
